
window.MAV6Games=window.MAV6Games||{};
function MA_makeGame(meta,mode){
 return function(ctx){
  let c=ctx.canvas,x=c.getContext("2d"),W=0,H=0,running=false,paused=false,score=0,start=0,last=0,raf=0,activity=0,done=false,state={};
  const fit=()=>{let d=devicePixelRatio||1;W=c.clientWidth;H=c.clientHeight;c.width=Math.max(1,W*d);c.height=Math.max(1,H*d);x.setTransform(d,0,0,d,0,0)};
  const bg=()=>{x.fillStyle="#050b15";x.fillRect(0,0,W,H);let g=x.createRadialGradient(W*.5,H*.4,20,W*.5,H*.4,Math.max(W,H)*.8);g.addColorStop(0,"#142b48");g.addColorStop(1,"#040811");x.fillStyle=g;x.fillRect(0,0,W,H)};
  const txt=(t,px,y,col="#ecf7ff",align="center")=>{x.fillStyle=col;x.font=`800 ${px}px system-ui`;x.textAlign=align;x.fillText(t,W/2,y)};
  function end(completed=false){if(done)return;done=true;running=false;cancelAnimationFrame(raf);MAAudio.gameOver();let duration=Math.max(0,Date.now()-start),old=MAStorage.get().scores[meta.id]||0,pb=score>old;ctx.reportResult({gameId:meta.id,result:completed?"complete":"gameover",score:Math.max(0,Math.floor(score)),completed,level:state.level||1,durationMs:duration,stats:state,activity,personalBest:pb});}
  function loop(t){if(!running)return;let dt=Math.min(50,t-last||16);last=t;if(!paused){update(dt);render()}raf=requestAnimationFrame(loop)}
  function update(dt){}
  function render(){bg();txt(meta.title,28,55);txt("Score "+Math.floor(score),20,88,"#62e6ff");txt("Tap / click / use keyboard",14,H-22,"#8fa8c0")}
  function startGame(){fit();running=true;paused=false;done=false;score=0;activity=0;start=Date.now();last=performance.now();state={};setup();raf=requestAnimationFrame(loop)}
  function setup(){}
  const api={create:()=>{fit();MAInput.bind(c);setup()},start:startGame,pause:()=>{paused=true},resume:()=>{paused=false},restart:()=>{done=false;startGame()},update,render,end,destroy:()=>{running=false;cancelAnimationFrame(raf)}};
  function setupMode(){
   setup=()=>{state={}; if(mode==="snake"){state.snake=[[5,5]];state.dir={x:1,y:0};state.food=[8,5];state.acc=0}
   if(mode==="pong"){state.p=[H/2-40];state.ball={x:W/2,y:H/2,vx:230,vy:160};state.ai=H/2-40}
   if(mode==="breakout"){state.ball={x:W/2,y:H-55,vx:180,vy:-180};state.px=W/2;state.bricks=[];for(let j=0;j<5;j++)for(let i=0;i<10;i++)state.bricks.push({x:20+i*(W-40)/10,y:90+j*25,w:(W-50)/10,h:18,on:1})}
   if(mode==="2048"){state.grid=Array.from({length:4},()=>Array(4).fill(0));addTile();addTile();state.moves=0}
   if(mode==="memory"){state.cards=Array.from({length:12},(_,i)=>Math.floor(i/2)).sort(()=>Math.random()-.5);state.open=[];state.matched=new Set();state.moves=0}
   if(mode==="reaction"){state.phase="wait";state.t=MAUtils.rand(900,2200);state.started=0}
   if(mode==="color"){state.colors=["CYAN","PINK","LIME","GOLD"];state.target=MAUtils.choice(state.colors);state.until=3000}
   if(mode==="tictactoe"){state.b=Array(9).fill("");state.turn="X"}
   if(mode==="basketball"){state.y=H-70;state.target={x:MAUtils.rand(80,W-80),y:MAUtils.rand(100,H-180)};state.shots=0}
   if(mode==="cricket"){state.ball=0;state.target=MAUtils.rand(30,70);state.runs=0}
   if(mode==="clicker"){state.coins=0;state.rate=1;let gd=MAStorage.get().gameData[meta.id]||{};let now=Date.now(),prev=gd.last||now;if(now>=prev){state.offline=Math.min(8*3600000,now-prev)/3600000*state.rate;state.coins=state.offline}state.last=now}
   if(mode==="arrow"){state.x=W/2;state.rows=[];state.t=0}
   if(mode==="fps"||mode==="target"){state.targets=[];spawnTarget()}
   if(mode==="highway"){state.car=W/2;state.obs=[];state.t=0}
   if(mode==="space"){state.ship=W/2;state.bullets=[];state.enemies=[];state.t=0}
   if(mode==="meteor"){state.x=W/2;state.obs=[];state.t=0}
   if(mode==="stack"){state.blocks=[{x:W/2-70,w:140,y:H-60}];state.falling={x:50,w:140,y:H-95,v:150}}
   if(mode==="flappy"){state.y=H/2;state.v=0;state.pipes=[];state.t=0}
   if(mode==="lightning"){state.pad=0;state.until=1500;state.next=MAUtils.rand(400,1300)}
   if(mode==="number"){state.n=1;state.items=[];for(let i=1;i<=12;i++)state.items.push({n:i,x:MAUtils.rand(50,W-50),y:MAUtils.rand(100,H-80)})}
   if(mode==="maze"){state.g=makeMaze(10,7);state.p={x:0,y:0};state.end={x:9,y:6}}
   if(mode==="word"){newWord()}
   if(mode==="tower"){state.base=3;state.enemies=[];state.t=0;state.towers=[]}
   if(mode==="balance"){state.x=W/2;state.v=0;state.t=0}
  };
  function addTile(){let z=[];state.grid.forEach((r,y)=>r.forEach((v,xx)=>{if(!v)z.push([xx,y])}));if(z.length){let q=z[Math.floor(Math.random()*z.length)];state.grid[q[1]][q[0]]=Math.random()<.9?2:4}}
  function slide(row){let a=row.filter(Boolean),out=[];for(let i=0;i<a.length;i++){if(a[i]===a[i+1]){out.push(a[i]*2);score+=a[i]*2;i++}else out.push(a[i])}while(out.length<4)out.push(0);return out}
  function move2048(dx,dy){let g=state.grid.map(r=>r.slice()),ng=Array.from({length:4},()=>Array(4).fill(0));if(dx){for(let y=0;y<4; y++){let r=dx>0?g[y].slice().reverse():g[y].slice();r=slide(r);if(dx>0)r.reverse();ng[y]=r}}else{for(let xx=0;xx<4;xx++){let r=[];for(let y=0;y<4;y++)r.push(g[y][xx]);if(dy>0)r.reverse();r=slide(r);if(dy>0)r.reverse();for(let y=0;y<4;y++)ng[y][xx]=r[y]}}if(JSON.stringify(g)!==JSON.stringify(ng)){state.grid=ng;state.moves++;activity++;addTile();MAAudio.score();if(!ng.flat().includes(0))end(true)}}
  function spawnTarget(){state.targets=[{x:MAUtils.rand(50,W-50),y:MAUtils.rand(110,H-70),r:28,life:2200}]}
  function newWord(){let words=["ARCADE","NEON","PIXEL","SNAKE","ROCKET","PONG","COMBO","LEVEL","TARGET","MAZE"];let w=MAUtils.choice(words);state.word=w;state.scr=w.split("").sort(()=>Math.random()-.5).join("");state.input=""}
  function makeMaze(w,h){let g=Array.from({length:h},()=>Array(w).fill(1));let st=[[0,0]];g[0][0]=0;while(st.length){let [cx,cy]=st[st.length-1],dirs=[[2,0],[0,2],[-2,0],[0,-2]].sort(()=>Math.random()-.5),ok=false;for(let [dx,dy] of dirs){let nx=cx+dx,ny=cy+dy;if(nx>=0&&nx<w&&ny>=0&&ny<h&&g[ny][nx]){g[cy+dy/2][cx+dx/2]=0;g[ny][nx]=0;st.push([nx,ny]);ok=true;break}}if(!ok)st.pop()}return g}
  function hitCircle(px,py,t){return Math.hypot(px-t.x,py-t.y)<=t.r}
  function pointer(){return ctx.input.touch}
  update=(dt)=>{
   activity++; let k=ctx.input.keys, p=pointer();
   if(mode==="snake"){state.acc+=dt;if(k.has("arrowup")||k.has("w"))state.dir={x:0,y:-1};if(k.has("arrowdown")||k.has("s"))state.dir={x:0,y:1};if(k.has("arrowleft")||k.has("a"))state.dir={x:-1,y:0};if(k.has("arrowright")||k.has("d"))state.dir={x:1,y:0};if(p.swipe){let s=p.swipe;state.dir=s==="up"?{x:0,y:-1}:s==="down"?{x:0,y:1}:s==="left"?{x:-1,y:0}:{x:1,y:0};p.swipe=null}if(state.acc>130){state.acc=0;let h={x:state.snake[0][0]+state.dir.x,y:state.snake[0][1]+state.dir.y};if(h[0]<0||h[0]>=20||h[1]<0||h[1]>=12||state.snake.some(q=>q[0]===h.x&&q[1]===h.y)){end(false);return}state.snake.unshift([h.x,h.y]);if(h.x===state.food[0]&&h.y===state.food[1]){score+=100;activity+=4;let z;do{z=[MAUtils.randi(0,19),MAUtils.randi(0,11)]}while(state.snake.some(q=>q[0]===z[0]&&q[1]===z[1]));state.food=z;MAAudio.score()}else state.snake.pop()}}
   else if(mode==="pong"){state.p[0]=MAUtils.clamp(state.p[0]+((k.has("arrowdown")||k.has("s"))?280*dt/1000:0)-((k.has("arrowup")||k.has("w"))?280*dt/1000:0),0,H-80);state.ai=MAUtils.clamp(state.ai+Math.sign(state.ball.y-(state.ai+40))*210*dt/1000,0,H-80);state.ball.x+=state.ball.vx*dt/1000;state.ball.y+=state.ball.vy*dt/1000;if(state.ball.y<8||state.ball.y>H-8)state.ball.vy*=-1;if(state.ball.x<28&&state.ball.y>state.p[0]&&state.ball.y<state.p[0]+80){state.ball.vx=Math.abs(state.ball.vx)*1.04;score+=10;activity+=2;MAAudio.hit()}if(state.ball.x>W-28&&state.ball.y>state.ai&&state.ball.y<state.ai+80)state.ball.vx=-Math.abs(state.ball.vx)*1.04;if(state.ball.x<0){end(false)}if(state.ball.x>W){end(true)}}
   else if(mode==="breakout"){let b=state.ball;state.px=MAUtils.clamp((p.down?p.x:state.px)||W/2,50,W-50);b.x+=b.vx*dt/1000;b.y+=b.vy*dt/1000;if(b.x<8||b.x>W-8)b.vx*=-1;if(b.y<70)b.vy=Math.abs(b.vy);if(b.y>H-75&&b.y<H-40&&Math.abs(b.x-state.px)<75)b.vy=-Math.abs(b.vy);for(let q of state.bricks){if(q.on&&b.x>q.x&&b.x<q.x+q.w&&b.y>q.y&&b.y<q.y+q.h){q.on=0;b.vy*=-1;score+=25;MAAudio.hit();break}}if(b.y>H){end(false)}if(state.bricks.every(q=>!q.on))end(true)}
   else if(mode==="2048"){if(k.has("arrowleft")){k.delete("arrowleft");move2048(-1,0)}if(k.has("arrowright")){k.delete("arrowright");move2048(1,0)}if(k.has("arrowup")){k.delete("arrowup");move2048(0,-1)}if(k.has("arrowdown")){k.delete("arrowdown");move2048(0,1)}if(p.swipe){let s=p.swipe;p.swipe=null;move2048(s==="left"?-1:s==="right"?1:0,s==="up"?-1:s==="down"?1:0)}}
   else if(mode==="memory"){if(p.down&&!state.lastTap){state.lastTap=1;let q=Math.floor(p.x/(W/4)),z=Math.floor((p.y-80)/((H-120)/3));if(q>=0&&q<4&&z>=0&&z<3){let i=z*4+q;if(!state.matched.has(i)&&!state.open.includes(i)){state.open.push(i);state.moves++;activity+=2;if(state.open.length===2){let [a,b]=state.open;if(state.cards[a]===state.cards[b]){state.matched.add(a);state.matched.add(b);score+=100;state.open=[];MAAudio.score();if(state.matched.size===12)end(true)}else setTimeout(()=>{state.open=[]},450)}}}}else if(!p.down)state.lastTap=0}
   else if(mode==="reaction"){if(state.phase==="wait"){state.t-=dt;if(state.t<=0){state.phase="go";state.started=performance.now();MAAudio.beep(850,.1)}}else if(state.phase==="go"&&p.down&&!state.tap){state.tap=1;state.reaction=performance.now()-state.started;score=Math.max(1,1000-state.reaction);state.phase="done";activity+=5;MAAudio.score()}else if(!p.down)state.tap=0;if(state.phase==="done"&&k.has(" "))end(true)}
   else if(mode==="color"){state.until-=dt;if(state.until<=0)end(false);if(p.down&&!state.tap){state.tap=1;let col=MAUtils.choice(state.colors);if(col===state.target){score+=50;activity+=2;MAAudio.score()}else score=Math.max(0,score-25);state.target=MAUtils.choice(state.colors);state.until=2200}}else if(!p.down)state.tap=0
   else if(mode==="tictactoe"){let idx=-1;if(p.down&&!state.tap){state.tap=1;let q=Math.floor(p.x/(W/3)),z=Math.floor((p.y-80)/((H-100)/3));if(q>=0&&q<3&&z>=0&&z<3)idx=z*3+q}if(!p.down)state.tap=0;if(idx>=0&&state.b[idx]===""){state.b[idx]="X";activity++;let w=win(state.b);if(w){score=500;end(true);return}if(!state.b.includes("")){end(false);return}let opts=state.b.map((v,i)=>v?null:i).filter(i=>i!==null);let mv=MAUtils.choice(opts);state.b[mv]="O";if(win(state.b)){end(false);return}}}
   else if(mode==="basketball"){state.target.x+=Math.sin(Date.now()/500)*.2;if(p.down&&!state.tap){state.tap=1;let d=Math.hypot(p.x-state.target.x,p.y-state.target.y);state.shots++;if(d<70){score+=100;activity+=3;MAAudio.score()}else score+=10;state.target={x:MAUtils.rand(60,W-60),y:MAUtils.rand(100,H-170)};if(state.shots>=10)end(true)}}else if(!p.down)state.tap=0
   else if(mode==="cricket"){state.ball=(state.ball+dt/8)%100;if(p.down&&!state.tap){state.tap=1;let d=Math.abs(state.ball-state.target);let runs=d<5?6:d<12?4:d<22?2:0;score+=runs*20;state.runs+=runs;activity+=runs?3:1;if(runs)MAAudio.score();if(state.runs>=30)end(true)}}else if(!p.down)state.tap=0
   else if(mode==="clicker"){if(p.down&&!state.tap){state.tap=1;state.coins+=state.rate;score+=state.rate;activity+=2;MAAudio.click()}if(!p.down)state.tap=0;if(k.has("u")){k.delete("u");if(state.coins>=20){state.coins-=20;state.rate++;score+=10}}MAStorage.get().gameData[meta.id]={last:Date.now(),rate:state.rate};if(Date.now()-start>30000)end(true)}
   else if(mode==="arrow"){state.t+=dt;if(state.t>700){state.t=0;state.rows.unshift({y:-30,g:MAUtils.randi(1,18)});state.rows.forEach(q=>q.y+=55);if(state.rows.length>12)state.rows.pop()}let mv=(k.has("arrowleft")||k.has("a")?-1:0)+(k.has("arrowright")||k.has("d")?1:0);state.x=MAUtils.clamp(state.x+mv*260*dt/1000,20,W-20);for(let q of state.rows){if(q.y>H-80&&q.y<H-20&&Math.abs(state.x-(q.g*W/20))<W/25){end(false);break}}score+=dt/20}
   else if(mode==="fps"||mode==="target"){state.targets.forEach(q=>q.life-=dt);if(state.targets[0]?.life<=0)end(false);if(p.down&&!state.tap){state.tap=1;let q=state.targets[0];if(q&&hitCircle(p.x,p.y,q)){score+=100;activity+=3;MAAudio.hit();spawnTarget()}}if(!p.down)state.tap=0}
   else if(mode==="highway"||mode==="meteor"){let mv=(k.has("arrowleft")||k.has("a")?-1:0)+(k.has("arrowright")||k.has("d")?1:0);state.x=MAUtils.clamp(state.x+mv*320*dt/1000,25,W-25);state.t+=dt;if(state.t>550){state.t=0;state.obs.push({x:MAUtils.rand(30,W-30),y:-40,r:20})}state.obs.forEach(q=>q.y+=(mode==="meteor"?250:210)*dt/1000);for(let q of state.obs){if(q.y>H-100&&q.y<H-30&&Math.abs(q.x-state.x)<35)end(false)}score+=dt/15}
   else if(mode==="space"){let mv=(k.has("arrowleft")||k.has("a")?-1:0)+(k.has("arrowright")||k.has("d")?1:0);state.ship=MAUtils.clamp(state.ship+mv*300*dt/1000,20,W-20);if(k.has(" ")&&!state.cool){state.bullets.push({x:state.ship,y:H-60});state.cool=150}state.cool=Math.max(0,(state.cool||0)-dt);state.t+=dt;if(state.t>650){state.t=0;state.enemies.push({x:MAUtils.rand(20,W-20),y:-20})}state.bullets.forEach(q=>q.y-=450*dt/1000);state.enemies.forEach(q=>q.y+=130*dt/1000);for(let b of state.bullets)for(let e of state.enemies)if(Math.hypot(b.x-e.x,b.y-e.y)<22){e.dead=1;b.dead=1;score+=100;MAAudio.hit()}state.bullets=state.bullets.filter(q=>!q.dead&&q.y>0);state.enemies=state.enemies.filter(q=>!q.dead&&q.y<H+30);if(state.enemies.some(e=>e.y>H-70))end(false)}
   else if(mode==="stack"){state.falling.x+=state.falling.v*dt/1000;if(state.falling.x<20||state.falling.x+state.falling.w>W-20)state.falling.v*=-1;if((p.down&&!state.tap)||k.has(" ")){state.tap=1;k.delete(" ");let top=state.blocks[state.blocks.length-1],a=Math.max(top.x,state.falling.x),b=Math.min(top.x+top.w,state.falling.x+state.falling.w);if(b<=a){end(false)}else{let nw=b-a;score+=nw;state.blocks.push({x:a,w:nw,y:top.y-35});state.falling={x:20,w:nw,y:top.y-70,v:state.falling.v*1.04};activity+=2;if(state.blocks.length>12)end(true)}}if(!p.down)state.tap=0}
   else if(mode==="flappy"){state.v+=700*dt/1000;state.y+=state.v*dt/1000;if(k.has(" ")||p.down){state.v=-300;k.delete(" ");state.tap=1}if(state.y<10||state.y>H-20)end(false);state.t+=dt;if(state.t>1300){state.t=0;state.pipes.push({x:W+30,g:MAUtils.rand(100,H-180),gap:145})}state.pipes.forEach(q=>q.x-=180*dt/1000);for(let q of state.pipes){if(q.x<60&&q.x+45>30&&(state.y<q.g-q.gap/2||state.y>q.g+q.gap/2))end(false)}score+=dt/30}
   else if(mode==="lightning"){state.next-=dt;if(state.next<=0){state.pad=MAUtils.randi(0,3);state.until=1200;state.next=MAUtils.rand(700,1600)}state.until-=dt;if(p.down&&!state.tap){state.tap=1;let idx=Math.floor(p.x/(W/4));if(idx===state.pad&&state.until>0){score+=Math.max(20,Math.floor(state.until));activity+=4;MAAudio.score()}else end(false)}}else if(!p.down)state.tap=0
   else if(mode==="number"){if(p.down&&!state.tap){state.tap=1;let q=state.items.find(z=>Math.hypot(p.x-z.x,p.y-z.y)<30&&z.n===state.n);if(q){q.hit=1;state.n++;score+=50;activity+=2;if(state.n>12)end(true)}}}else if(!p.down)state.tap=0
   else if(mode==="maze"){let mv=null;if(k.has("arrowleft"))mv=[-1,0],k.delete("arrowleft");if(k.has("arrowright"))mv=[1,0],k.delete("arrowright");if(k.has("arrowup"))mv=[0,-1],k.delete("arrowup");if(k.has("arrowdown"))mv=[0,1],k.delete("arrowdown");if(p.swipe){let s=p.swipe;p.swipe=null;mv=s==="left"?[-1,0]:s==="right"?[1,0]:s==="up"?[0,-1]:[0,1]}if(mv){let nx=state.p.x+mv[0],ny=state.p.y+mv[1];if(nx>=0&&ny>=0&&nx<10&&ny<7&&!state.g[ny][nx]){state.p={x:nx,y:ny};activity++;score+=5;if(nx===9&&ny===6)end(true)}}}
   else if(mode==="word"){if(p.down&&!state.tap){state.tap=1;let letters=(prompt("Unscramble: "+state.scr+"\\nType the answer")||"").trim().toUpperCase();if(letters===state.word){score=500;activity+=5;end(true)}else end(false)}}else if(!p.down)state.tap=0
   else if(mode==="tower"){state.t+=dt;if(state.t>900){state.t=0;state.enemies.push({x:0,y:H/2+MAUtils.rand(-60,60),hp:3})}for(let e of state.enemies){for(let t of state.towers){if(Math.hypot(e.x-t.x,e.y-t.y)<180)e.hp-=dt/1000*2}e.x+=35*dt/1000}if(p.down&&!state.tap){state.tap=1;if(state.towers.length<6&&score>=50){score-=50;state.towers.push({x:p.x,y:p.y});activity+=2}}if(!p.down)state.tap=0;state.enemies=state.enemies.filter(e=>{if(e.hp<=0){score+=100;return false}if(e.x>W-20){state.base--;return false}return true});if(state.base<=0)end(false);if(score>1000)end(true)}
   else if(mode==="balance"){let mv=(k.has("arrowleft")||k.has("a")?-1:0)+(k.has("arrowright")||k.has("d")?1:0);state.v+=mv*380*dt/1000;state.v*=.98;state.x+=state.v*dt/1000;let center=W/2+Math.sin(Date.now()/800)*W*.2;state.x=MAUtils.clamp(state.x,20,W-20);if(Math.abs(state.x-center)>120)end(false);score+=dt/20}
  };
  function win(b){return [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(q=>b[q[0]]&&b[q[0]]===b[q[1]]&&b[q[1]]===b[q[2]])}
  render=()=>{bg();txt(meta.title,26,35);txt("Score "+Math.floor(score),17,62,"#62e6ff");let k=ctx.input.keys,p=ctx.input.touch;
   if(mode==="snake"){let cw=W/20,ch=(H-85)/12;x.fillStyle="#0b2a39";x.fillRect(0,80,W,H-80);x.fillStyle="#59e391";state.snake.forEach((q,i)=>x.fillRect(q[0]*cw+2,82+q[1]*ch+2,cw-4,ch-4));x.fillStyle="#ff5f7a";x.beginPath();x.arc(state.food[0]*cw+cw/2,82+state.food[1]*ch+ch/2,Math.min(cw,ch)*.35,0,7);x.fill()}
   else if(mode==="pong"){x.fillStyle="#62e6ff";x.fillRect(12,state.p[0],10,80);x.fillStyle="#a779ff";x.fillRect(W-22,state.ai,10,80);x.fillStyle="#fff";x.beginPath();x.arc(state.ball.x,state.ball.y,7,0,7);x.fill()}
   else if(mode==="breakout"){x.fillStyle="#62e6ff";x.fillRect(state.px-65,H-45,130,12);state.bricks.forEach((q,i)=>{if(q.on){x.fillStyle=i%2?"#a779ff":"#62e6ff";x.shadowBlur=10;x.shadowColor=x.fillStyle;x.fillRect(q.x,q.y,q.w-4,q.h);x.shadowBlur=0}});x.fillStyle="#fff";x.beginPath();x.arc(state.ball.x,state.ball.y,7,0,7);x.fill()}
   else if(mode==="2048"){for(let y=0;y<4;y++)for(let xx=0;xx<4;xx++){let v=state.grid[y][xx];x.fillStyle=v?"#24506a":"#0b1828";x.fillRect(30+xx*(W-60)/4,95+y*(H-130)/4,(W-75)/4,(H-145)/4);if(v)txt(String(v),Math.min(30,(W-80)/7),125+y*(H-130)/4,"#fff")}}
   else if(mode==="memory"){for(let i=0;i<12;i++){let xx=i%4,yy=Math.floor(i/4),ox=25+xx*(W-50)/4,oy=90+yy*(H-115)/3;x.fillStyle=state.open.includes(i)||state.matched.has(i)?"#1e4961":"#101f33";x.fillRect(ox,oy,(W-65)/4,(H-135)/3);if(state.open.includes(i)||state.matched.has(i))txt(["◆","●","▲","★","✦","✚"][state.cards[i]],26,oy+40+yy*0,"#fff")}}
   else if(mode==="reaction"){txt(state.phase==="wait"?"WAIT...":state.phase==="go"?"TAP!":"RESULT",48,H/2,"#59e391");if(state.reaction)txt(Math.round(state.reaction)+" ms",28,H/2+50)}
   else if(mode==="color"){txt(state.target,42,H/2,"#62e6ff");txt("Tap when the shown color is correct",15,H/2+45)}
   else if(mode==="tictactoe"){for(let i=1;i<3;i++){x.strokeStyle="#ffffff33";x.lineWidth=3;x.beginPath();x.moveTo(i*W/3,90);x.lineTo(i*W/3,H-10);x.moveTo(0,90+i*(H-100)/3);x.lineTo(W,90+i*(H-100)/3);x.stroke()}state.b.forEach((v,i)=>txt(v,48,(i%3)*W/3+W/6, "X"===v?"#62e6ff":"#ff6ea8"));txt("Tap a square",16,H-20,"#8fa8c0")}
   else if(mode==="basketball"){x.fillStyle="#1d344f";x.fillRect(0,H-40,W,40);x.fillStyle="#ff9a3d";x.beginPath();x.arc(state.target.x,state.target.y,28,0,7);x.fill();txt("10 shots",16,90)}
   else if(mode==="cricket"){x.fillStyle="#1b5d43";x.fillRect(20,110,W-40,H-170);x.fillStyle="#fff";x.fillRect(W/2-5,120,10,H-190);x.fillStyle="#ff5f7a";x.beginPath();x.arc(20+(W-40)*state.ball/100,H/2,10,0,7);x.fill();txt("Tap when the ball crosses the target zone",15,H-35)}
   else if(mode==="clicker"){txt("🪙",80,H/2-10);txt("Tap anywhere • U upgrades rate for 20 coins",15,H/2+80)}
   else if(mode==="arrow"){x.fillStyle="#18283c";state.rows.forEach(q=>{x.fillRect(q.g*W/20,q.y,W/20-3,30)});x.fillStyle="#59e391";x.beginPath();x.arc(state.x,H-45,16,0,7);x.fill()}
   else if(mode==="fps"||mode==="target"){let q=state.targets[0];if(q){x.strokeStyle="#ff5f7a";x.lineWidth=5;x.beginPath();x.arc(q.x,q.y,q.r,0,7);x.stroke();x.beginPath();x.moveTo(q.x-q.r-8,q.y);x.lineTo(q.x+q.r+8,q.y);x.moveTo(q.x,q.y-q.r-8);x.lineTo(q.x,q.y+q.r+8);x.stroke()}}
   else if(mode==="highway"||mode==="meteor"){x.fillStyle="#142236";x.fillRect(0,80,W,H-80);x.fillStyle="#fff";for(let y=90;y<H;y+=70)x.fillRect(W/2-3,y,6,35);x.fillStyle="#62e6ff";x.fillRect(state.x-18,H-70,36,48);state.obs.forEach(q=>{x.fillStyle=mode==="meteor"?"#ff5f7a":"#a779ff";x.beginPath();x.arc(q.x,q.y,q.r,0,7);x.fill()})}
   else if(mode==="space"){x.fillStyle="#62e6ff";x.beginPath();x.moveTo(state.ship,H-55);x.lineTo(state.ship-18,H-20);x.lineTo(state.ship+18,H-20);x.closePath();x.fill();x.fillStyle="#fff";state.bullets.forEach(q=>x.fillRect(q.x-2,q.y,4,10));x.fillStyle="#ff5f7a";state.enemies.forEach(q=>{x.beginPath();x.arc(q.x,q.y,16,0,7);x.fill()})}
   else if(mode==="stack"){state.blocks.forEach((q,i)=>{x.fillStyle=i%2?"#a779ff":"#62e6ff";x.fillRect(q.x,q.y,q.w,28)});x.fillStyle="#fff";x.fillRect(state.falling.x,state.falling.y,state.falling.w,28)}
   else if(mode==="flappy"){x.fillStyle="#59e391";x.beginPath();x.arc(60,state.y,15,0,7);x.fill();state.pipes.forEach(q=>{x.fillStyle="#62e6ff";x.fillRect(q.x,80,45,q.g-q.gap/2-80);x.fillRect(q.x,q.g+q.gap/2,45,H-q.g-q.gap/2)})}
   else if(mode==="lightning"){for(let i=0;i<4;i++){x.fillStyle=i===state.pad?"#59e391":"#14243a";x.fillRect(i*W/4+8,150,W/4-16,H-230)}txt("HIT PAD "+(state.pad+1),28,105)}
   else if(mode==="number"){state.items.forEach(q=>{if(!q.hit)txt(String(q.n),26,q.y,q.n===state.n?"#59e391":"#8fa8c0")});txt("Next: "+state.n,18,95)}
   else if(mode==="maze"){let cw=Math.min((W-40)/10,(H-130)/7),ox=(W-cw*10)/2,oy=100;for(let yy=0;yy<7;yy++)for(let xx=0;xx<10;xx++){x.fillStyle=state.g[yy][xx]?"#13253a":"#07131f";x.fillRect(ox+xx*cw,oy+yy*cw,cw-2,cw-2)}x.fillStyle="#59e391";x.beginPath();x.arc(ox+(state.p.x+.5)*cw,oy+(state.p.y+.5)*cw,cw*.3,0,7);x.fill();x.fillStyle="#ff5f7a";x.fillRect(ox+9.1*cw,oy+6.1*cw,cw*.7,cw*.7)}
   else if(mode==="word"){txt(state.scr,42,H/2,"#62e6ff");txt("Tap to enter the answer",16,H/2+55)}
   else if(mode==="tower"){x.fillStyle="#59e391";x.fillRect(W-25,H/2-50,15,100);state.towers.forEach(t=>{x.fillStyle="#62e6ff";x.beginPath();x.arc(t.x,t.y,16,0,7);x.fill()});state.enemies.forEach(e=>{x.fillStyle="#ff5f7a";x.beginPath();x.arc(e.x,e.y,12,0,7);x.fill()});txt("Tap to place tower (50)",15,95)}
   else if(mode==="balance"){let center=W/2+Math.sin(Date.now()/800)*W*.2;x.strokeStyle="#62e6ff";x.lineWidth=8;x.beginPath();x.moveTo(center-120,H-80);x.lineTo(center+120,H-80);x.stroke();x.fillStyle="#ff9a3d";x.beginPath();x.arc(state.x,H-105,18,0,7);x.fill()}
   else {txt("Playable arcade mode",24,H/2)}
  };
  }
  setupMode();return api;
 };
}
window.MAV6Games["pong"]=MA_makeGame({"id": "pong", "title": "Pong", "category": "classic", "difficulty": "easy", "description": "Classic paddle duel against a smart CPU.", "icon": "\ud83c\udfd3"},"pong");
